/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Alexander Verbruggen (https://sketchfab.com/AlexanderVerbruggen)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/stylized-interbellum-rustborn-plane-18148ea4dfec4038bf5c263d996a94c5
Title: Stylized Interbellum rustborn plane
*/

import * as THREE from 'three'
import React, { useEffect, useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    StaticPlaneParts_standardSurface1_0: THREE.Mesh
    TopRightWing_standardSurface1_0: THREE.Mesh
    BottomRighWing_standardSurface1_0: THREE.Mesh
    TopLeftWing_standardSurface1_0: THREE.Mesh
    BackLeftWing_standardSurface1_0: THREE.Mesh
    polySurface385_standardSurface1_0: THREE.Mesh
    BackWing_standardSurface1_0: THREE.Mesh
    BottomLeftWing_standardSurface1_0: THREE.Mesh
    Prop_standardSurface1_0: THREE.Mesh
    LeftWingRope_standardSurface1_0: THREE.Mesh
    RightWingRope_standardSurface1_0: THREE.Mesh
  }
  materials: {
    standardSurface1: THREE.MeshStandardMaterial
  }
}

type ActionName = 'Flying'
type GLTFActions = Record<ActionName, THREE.AnimationAction>

export function Plane(props: JSX.IntrinsicElements['group']) {
  const group = useRef<THREE.Group>()
  const { nodes, materials, animations } = useGLTF('/plane.glb') as GLTFResult
  const { actions } = useAnimations<any>(animations, group)

  useEffect(() => {
    actions['Flying'].play()
  }, []);

  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <group name="Sketchfab_model" rotation={[-1.513, -0.039, 3.128]}>
          <group name="8c0c322551dd4ab39df1b9ded8f3c6ccfbx" rotation={[Math.PI / 2, 0, 0]}>
            <group name="Object_2">
              <group name="RootNode">
                <group name="RustbornPlane" position={[-0.003, 0.001, 0]} scale={0.01}>
                  <group
                    name="StaticPlaneParts"
                    position={[0, -0.372, 0.909]}
                    rotation={[-0.001, -0.025, -0.047]}>
                    <mesh
                      name="StaticPlaneParts_standardSurface1_0"
                      castShadow
                      receiveShadow
                      geometry={nodes.StaticPlaneParts_standardSurface1_0.geometry}
                      material={materials.standardSurface1}
                    />
                    <group
                      name="TopRightWing"
                      position={[3.526, 2.013, -2.14]}
                      rotation={[-0.074, 0, 0]}>
                      <mesh
                        name="TopRightWing_standardSurface1_0"
                        castShadow
                        receiveShadow
                        geometry={nodes.TopRightWing_standardSurface1_0.geometry}
                        material={materials.standardSurface1}
                      />
                    </group>
                    <group
                      name="BottomRighWing"
                      position={[3.749, -0.46, -1.159]}
                      rotation={[-0.074, 0, 0]}>
                      <mesh
                        name="BottomRighWing_standardSurface1_0"
                        castShadow
                        receiveShadow
                        geometry={nodes.BottomRighWing_standardSurface1_0.geometry}
                        material={materials.standardSurface1}
                      />
                    </group>
                    <group
                      name="TopLeftWing"
                      position={[-3.547, 2.013, -2.083]}
                      rotation={[0.164, 0, 0]}>
                      <mesh
                        name="TopLeftWing_standardSurface1_0"
                        castShadow
                        receiveShadow
                        geometry={nodes.TopLeftWing_standardSurface1_0.geometry}
                        material={materials.standardSurface1}
                      />
                    </group>
                    <group
                      name="BackLeftWing"
                      position={[-1.494, 0.64, 4.265]}
                      rotation={[0.2, 0, 0]}>
                      <mesh
                        name="BackLeftWing_standardSurface1_0"
                        castShadow
                        receiveShadow
                        geometry={nodes.BackLeftWing_standardSurface1_0.geometry}
                        material={materials.standardSurface1}
                      />
                    </group>
                    <group name="polySurface385" position={[1.46, 0.64, 4.258]}>
                      <mesh
                        name="polySurface385_standardSurface1_0"
                        castShadow
                        receiveShadow
                        geometry={nodes.polySurface385_standardSurface1_0.geometry}
                        material={materials.standardSurface1}
                      />
                    </group>
                    <group name="BackWing" position={[0, 1.418, 4.893]} rotation={[0, -0.088, 0]}>
                      <mesh
                        name="BackWing_standardSurface1_0"
                        castShadow
                        receiveShadow
                        geometry={nodes.BackWing_standardSurface1_0.geometry}
                        material={materials.standardSurface1}
                      />
                    </group>
                    <group
                      name="BottomLeftWing"
                      position={[-3.759, -0.46, -1.156]}
                      rotation={[0.155, 0, 0]}>
                      <mesh
                        name="BottomLeftWing_standardSurface1_0"
                        castShadow
                        receiveShadow
                        geometry={nodes.BottomLeftWing_standardSurface1_0.geometry}
                        material={materials.standardSurface1}
                      />
                    </group>
                    <group name="Prop" position={[0, 0.515, -5.331]} rotation={[0, 0, -2.678]}>
                      <mesh
                        name="Prop_standardSurface1_0"
                        castShadow
                        receiveShadow
                        geometry={nodes.Prop_standardSurface1_0.geometry}
                        material={materials.standardSurface1}
                      />
                    </group>
                    <group name="LeftWingRope" position={[-4.963, 0.74, -1.033]} scale={0.966}>
                      <mesh
                        name="LeftWingRope_standardSurface1_0"
                        castShadow
                        receiveShadow
                        geometry={nodes.LeftWingRope_standardSurface1_0.geometry}
                        material={materials.standardSurface1}
                      />
                    </group>
                    <group name="RightWingRope" position={[4.955, 0.874, -1.053]}>
                      <mesh
                        name="RightWingRope_standardSurface1_0"
                        castShadow
                        receiveShadow
                        geometry={nodes.RightWingRope_standardSurface1_0.geometry}
                        material={materials.standardSurface1}
                      />
                    </group>
                  </group>
                </group>
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/plane.glb')
