/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from 'three'
import React, { useRef, useMemo } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    ['11817_Zepplin_Cab']: THREE.Mesh
    ['11817_Zepplin_Engine']: THREE.Mesh
    ['11817_Zepplin_Motor']: THREE.Mesh
    ['11817_Zepplin_Mount']: THREE.Mesh
    ['11817_Zepplin_Shassis_Mount']: THREE.Mesh
    ['11817_Zepplin_Shassis_Mount_2']: THREE.Mesh
    ['11817_Zepplin_Metal']: THREE.Mesh
    ['11817_Zepplin_Wheel']: THREE.Mesh
    ['11817_Zepplin_Wings']: THREE.Mesh
    ['11817_Zepplin_Balloon']: THREE.Mesh
    ['11817_Zepplin_front']: THREE.Mesh
    ['11817_Zepplin_Wheel2']: THREE.Mesh
    ['11817_Zepplin_Tube']: THREE.Mesh
  }
  materials: {
    ['11817_Zepplin_Cab']: THREE.MeshStandardMaterial
    ['11817_Zepplin']: THREE.MeshStandardMaterial
    ['11817_Zepplin_metall']: THREE.MeshStandardMaterial
    ['11817_Zepplin_Balon']: THREE.MeshStandardMaterial
    ['11817_Zepplin_Wheel']: THREE.MeshStandardMaterial
  }
}

export function Zeppelin(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/zeppelin.glb') as GLTFResult;

  useMemo(() => {
    materials['11817_Zepplin_metall'].color.set("#2e2e2e");
    materials['11817_Zepplin_Balon'].color.set("#eeffce");
    //materials['11817_Zepplin_Wheel'].color.set("red")
    materials['11817_Zepplin'].color.set("#ffd000");
    materials['11817_Zepplin_Cab'].color.set("#87adbd");

  }, [materials]);

  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes['11817_Zepplin_Cab'].geometry} material={materials['11817_Zepplin_Cab']} />
      <mesh geometry={nodes['11817_Zepplin_Engine'].geometry} material={materials['11817_Zepplin']} />
      <mesh geometry={nodes['11817_Zepplin_Motor'].geometry} material={materials['11817_Zepplin']} />
      <mesh geometry={nodes['11817_Zepplin_Mount'].geometry} material={materials['11817_Zepplin']} />
      <mesh geometry={nodes['11817_Zepplin_Shassis_Mount'].geometry} material={materials['11817_Zepplin_metall']} />
      <mesh geometry={nodes['11817_Zepplin_Shassis_Mount_2'].geometry} material={materials['11817_Zepplin_metall']} />
      <mesh geometry={nodes['11817_Zepplin_Metal'].geometry} material={materials['11817_Zepplin_metall']} />
      <mesh geometry={nodes['11817_Zepplin_Wheel'].geometry} material={materials['11817_Zepplin_metall']} />
      <mesh geometry={nodes['11817_Zepplin_Wings'].geometry} material={materials['11817_Zepplin']} />
      <mesh geometry={nodes['11817_Zepplin_Balloon'].geometry} material={materials['11817_Zepplin_Balon']} />
      <mesh geometry={nodes['11817_Zepplin_front'].geometry} material={materials['11817_Zepplin']} />
      <mesh geometry={nodes['11817_Zepplin_Wheel2'].geometry} material={materials['11817_Zepplin_Wheel']} />
      <mesh geometry={nodes['11817_Zepplin_Tube'].geometry} material={materials['11817_Zepplin_metall']} />
    </group>
  )
}

useGLTF.preload('/zeppelin.glb')
